apiVersion: v1
kind: Service
metadata:
  name: python-flask-kube-svc
spec:
  type: LoadBalancer
  selector:
    app: python-flask-kube
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000